import { Video, Artist, KPIData, ChartDataPoint, Transaction } from "@/types";

export const mockArtists: Artist[] = [
  {
    id: "1",
    name: "La Doña",
    bio: "Artista urbana de Ciudad de México",
    avatar: "https://picsum.photos/seed/artist1/200/200",
    coverImage: "https://picsum.photos/seed/cover1/1200/400",
    followers: 125000,
    verified: true,
    genres: ["Urban", "Hip-Hop"],
  },
  {
    id: "2",
    name: "Carin León",
    bio: "El Beto del Regional Mexicano",
    avatar: "https://picsum.photos/seed/artist2/200/200",
    coverImage: "https://picsum.photos/seed/cover2/1200/400",
    followers: 980000,
    verified: true,
    genres: ["Regional Mexicano", "Banda"],
  },
  {
    id: "3",
    name: "Nathy Peluso",
    bio: "Cantante, rapera y compositora argentina",
    avatar: "https://picsum.photos/seed/artist3/200/200",
    coverImage: "https://picsum.photos/seed/cover3/1200/400",
    followers: 430000,
    verified: true,
    genres: ["Pop", "Soul", "Hip-Hop"],
  },
  {
    id: "4",
    name: "Trueno",
    bio: "Freestyler y rapero de Buenos Aires",
    avatar: "https://picsum.photos/seed/artist4/200/200",
    coverImage: "https://picsum.photos/seed/cover4/1200/400",
    followers: 560000,
    verified: false,
    genres: ["Hip-Hop", "Freestyle"],
  },
  {
    id: "5",
    name: "Sofía Reyes",
    bio: "Pop en español con sabor internacional",
    avatar: "https://picsum.photos/seed/artist5/200/200",
    coverImage: "https://picsum.photos/seed/cover5/1200/400",
    followers: 320000,
    verified: true,
    genres: ["Pop", "Latin Pop"],
  },
  {
    id: "6",
    name: "Residente",
    bio: "Leyenda del rap latinoamericano",
    avatar: "https://picsum.photos/seed/artist6/200/200",
    coverImage: "https://picsum.photos/seed/cover6/1200/400",
    followers: 1200000,
    verified: true,
    genres: ["Hip-Hop", "Rap", "Latin Fusion"],
  },
];

export const mockVideos: Video[] = [
  {
    id: "1",
    title: "Mi Forma de Ser",
    description: "Video oficial",
    thumbnail: "https://picsum.photos/seed/video1/320/180",
    hlsUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    duration: 215,
    views: 1250000,
    likes: 45000,
    artistId: "1",
    artistName: "La Doña",
    genres: ["Urban"],
    publishedAt: "2024-01-15",
    status: "published",
  },
  {
    id: "2",
    title: "Según Quién",
    description: "Éxito del año",
    thumbnail: "https://picsum.photos/seed/video2/320/180",
    hlsUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    duration: 243,
    views: 3800000,
    likes: 120000,
    artistId: "2",
    artistName: "Carin León",
    genres: ["Regional Mexicano"],
    publishedAt: "2024-02-01",
    status: "published",
  },
  {
    id: "3",
    title: "La Sandunguera",
    description: "Nuevo sencillo",
    thumbnail: "https://picsum.photos/seed/video3/320/180",
    hlsUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    duration: 198,
    views: 870000,
    likes: 32000,
    artistId: "3",
    artistName: "Nathy Peluso",
    genres: ["Pop", "Soul"],
    publishedAt: "2024-02-20",
    status: "published",
  },
  {
    id: "4",
    title: "Mamichula",
    description: "feat. Bizarrap",
    thumbnail: "https://picsum.photos/seed/video4/320/180",
    hlsUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    duration: 187,
    views: 5200000,
    likes: 200000,
    artistId: "4",
    artistName: "Trueno",
    genres: ["Hip-Hop"],
    publishedAt: "2024-01-05",
    status: "published",
  },
  {
    id: "5",
    title: "1, 2, 3",
    description: "Con Jason Derulo",
    thumbnail: "https://picsum.photos/seed/video5/320/180",
    hlsUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    duration: 212,
    views: 2100000,
    likes: 78000,
    artistId: "5",
    artistName: "Sofía Reyes",
    genres: ["Pop"],
    publishedAt: "2024-03-01",
    status: "published",
  },
  {
    id: "6",
    title: "Antes de los Tiro",
    description: "Álbum nuevo",
    thumbnail: "https://picsum.photos/seed/video6/320/180",
    hlsUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    duration: 267,
    views: 4500000,
    likes: 165000,
    artistId: "6",
    artistName: "Residente",
    genres: ["Hip-Hop", "Rap"],
    publishedAt: "2024-02-10",
    status: "published",
  },
  {
    id: "7",
    title: "Barrio Rojo",
    description: "Video musical",
    thumbnail: "https://picsum.photos/seed/video7/320/180",
    hlsUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    duration: 223,
    views: 680000,
    likes: 21000,
    artistId: "1",
    artistName: "La Doña",
    genres: ["Urban"],
    publishedAt: "2024-03-10",
    status: "published",
  },
  {
    id: "8",
    title: "Rondando",
    description: "En vivo",
    thumbnail: "https://picsum.photos/seed/video8/320/180",
    hlsUrl: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
    duration: 195,
    views: 420000,
    likes: 15000,
    artistId: "3",
    artistName: "Nathy Peluso",
    genres: ["Pop"],
    publishedAt: "2024-03-15",
    status: "draft",
  },
];

export const mockKPIData: KPIData = {
  totalViews: 1247832,
  viewsChange: 12.5,
  followers: 45231,
  followersChange: 8.3,
  revenue: 3842.5,
  revenueChange: 23.1,
  totalVideos: 24,
  videosChange: 4,
};

export const mockViewsData: ChartDataPoint[] = Array.from({ length: 30 }, (_, i) => {
  const date = new Date();
  date.setDate(date.getDate() - (29 - i));
  return {
    date: date.toLocaleDateString("es-MX", { month: "short", day: "numeric" }),
    views: Math.floor(Math.random() * 50000) + 20000,
  };
});

export const mockRevenueData: ChartDataPoint[] = [
  { date: "Sep", revenue: 1200 },
  { date: "Oct", revenue: 1800 },
  { date: "Nov", revenue: 2100 },
  { date: "Dic", revenue: 3200 },
  { date: "Ene", revenue: 2800 },
  { date: "Feb", revenue: 3842 },
];

export const mockTransactions: Transaction[] = [
  {
    id: "txn1",
    date: "2024-03-15",
    amount: 245.5,
    currency: "USD",
    method: "stripe",
    status: "completed",
    description: "Monetización por vistas",
  },
  {
    id: "txn2",
    date: "2024-03-10",
    amount: 180.0,
    currency: "USD",
    method: "paypal",
    status: "completed",
    description: "Pagos de suscriptores",
  },
  {
    id: "txn3",
    date: "2024-03-05",
    amount: 320.75,
    currency: "USD",
    method: "mercadopago",
    status: "completed",
    description: "Ingresos de publicidad",
  },
  {
    id: "txn4",
    date: "2024-02-28",
    amount: 0.025,
    currency: "ETH",
    method: "crypto",
    status: "pending",
    description: "NFT royalties",
  },
  {
    id: "txn5",
    date: "2024-02-20",
    amount: 150.0,
    currency: "USD",
    method: "stripe",
    status: "completed",
    description: "Monetización por vistas",
  },
  {
    id: "txn6",
    date: "2024-02-15",
    amount: 75.25,
    currency: "USD",
    method: "paypal",
    status: "failed",
    description: "Pago rechazado",
  },
];
